_wandb:
    value:
        cli_version: 0.26.0
        e:
            3y6pzp0gxkagamnklpu3rchui2oligg1:
                codePath: src/ssl_model/train_ssl.py
                codePathLocal: src/ssl_model/train_ssl.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "152391778304"
                        used: "119039377408"
                email: ramy.gharbi@esprit.tn
                executable: /home/ramy/miniconda3/envs/marketmind/bin/python
                git:
                    commit: fb0cfae562cfabc732d5f5452710b8ec2907acf7
                    remote: https://github.com/Ramyghr/marketmind.git
                host: ramy
                memory:
                    total: "16543481856"
                os: Linux-6.14.0-29-generic-x86_64-with-glibc2.39
                program: /home/ramy/Documents/MarketMind_PFE/MarketMind/src/ssl_model/train_ssl.py
                python: CPython 3.10.20
                root: /home/ramy/Documents/MarketMind_PFE/MarketMind
                startedAt: "2026-04-27T14:32:44.320210Z"
                writerId: 3y6pzp0gxkagamnklpu3rchui2oligg1
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.10.20
            "5": 0.26.0
            "12": 0.26.0
            "13": linux-x86_64
batch_size:
    value: 256
data:
    value: 2018-2024
embed_dim:
    value: 128
epochs:
    value: 5
lr:
    value: 0.0003
temperature:
    value: 0.07
